= Collaboration

[abstract]
Working with engineers and fellow tech writers to ship complete, accurate, useful, and engaging docs every time.

== Working with Existing Development Processes

Engineers typically expect technical writers to work around them.
Tech writers tend not to have much power in the situation.
I cannot stress enough how important it is to minimize disruption to developers' flow, even though sometimes disruption is precisely what is called for.

If you track developers' work in a project-management system (including a Kanban board or other dashboard-style instrumentation), you have probably found a systematic way to communicate with developers through it.
I won't go into the boring details of our solution, but we used JIRA, configured with a field for *Release Notes*, which will be exported to source prior to compiling the docs.

Our JIRA also has an issue type called "Docs Sub-Task", which is a way for engineers to create stubs, assigned to themselves, for documenting work that is scheduled or underway.
This way, I can see these tickets in the pipeline as flags for work that should be hitting my desk soon.

This is an elaborate alternative to tagging the work ticket "Needs Docs" or something.
In our case, we need a way to ensure code tickets don't get closed until their associated documentation work is ready, but we also do need a place for the developer to stick their notes.
The next iteration of this system that we'll test will hopefully lighten the load.

== Adapting Dev Workflows to Sync with Docs

// TODO section-start

== Tech Writers Are Not Stenographers

Some professional writers have horror stories about subject-matter experts treating them like assistants.
Yet I have heard tech writers remark that they have no choice but to let engineers do most of the writing, since it's their code, their concept, and so forth.

Tech writers all know that sometimes, in explaining new or complicated aspects of a product to us, SMEs practically write the whole segment.
I find myself copy editing instructions as often as writing them from experience first.
Nevertheless, good documentarians distinguish themselves by facilitating the production of content.
When we can write fresh copy, we do.
When we need to draw it out of developers, we make the process as painless as possible.

I imagine some professional tech writers have been muttering at half these pages, “As if, you lucky sonofa -- ”
I get it that not all are lucky enough to find themselves working with teams that highly value or elevate documentation.
There are different ways to approach this problem that may work better in various organizations; I would not purport to number such problem-solving among my skills.
However, I do know something about helping engineers see documentation differently than they've come to expect.

Every time a new engineer joins the team, I ping them on Slack and schedule a sync up.
I present a bit about how I approach documentation, as well as what is expected from them.
I want them to appreciate early on that my job is to help them do two of the parts of their job they wish could be automated: _accessing local knowledge_ and _documenting their own code_.
I also make it clear that I get traction for my initiatives from their support for and engagement with my procedures and technologies.

Put another way: without being immodest or blowing my own job out of proportion, I make sure everybody I work directly with understands that I take my job every bit as seriously as they take theirs.
I get to develop innovative systems for handling documentation that fit better and better into their current workflow, but only if they work with me.
To be fair, my experience at Rocana was that engineers strived to produce good docs just to please me, the way you might choose a decent standard of quality to strive for when carrying out a task in an adjacent field.
Engineers don't love writing docs, but when they have to generate a paragraph or a bunch of descriptions, they tend to appreciate having somebody around who will take that work seriously and mold it into shape.

=== The Promise of Good Docs

Various constituencies at Rocana depended on the docs that fell under my purview.
What each constituency needed the docs for was quite different, and it might seem like I was pulled in different directions trying to unite more and more sources.

No matter how we get it done, we basically have to make sure the docs are always:

* **S**earchable
* **O**rganized
* **A**ccurate
* **R**eadable
* **C**anonical
* **E**ditable
+
(Yes, I saw a mneumonic and I went for it.
_Accurate_ stayed in when _unimpeachable_ would have made _SOURCE_, because _editable_ implies impeachability.)

Let me introduce you to my immediate constituents.

Engineering::
+
--
I needed the engineering managers to see the devs were working more accurately and more efficiently under my systems.
I also needed them to see that, in collaboration with project managers, our documentation systems were catching the more passive documentation tasks, such as

* maintaining bill-of-materials requirements (a NOTICE file);
* announcing and following up on product feature deprecations;
* preparing content about the product for inclusion in the UI; and
* processing and copy editing the Release Notes and Changelog.
--

Product/CTO::
+
--
The Director of Product and the CTO together determined priorities for engineering resources.
I needed them to see the devs were doing more of the work in Java, JavaScript, and Golang that made up the digital assets we were selling.
All of that research, coding, and testing had truly exponential value, and the docs were just there to make sure that value could be realized.
That's humility I have, and it's perspective I don't mind Product having, as long as they appreciate that the docs form a critical layer, even if not a profit-magnifying one.

Mind you, I had to deduct from my systems' return on investment for any engineering time I depended on to establish and maintain tooling, as well as time spent reorienting the team to some new workflow routine.
I had to be judicious with the engineering resources I was afforded.
--

Support and Field Engineers::
+
--
The other constituency I dealt with directly at Rocana was made up of engineers in our Customer Success department, as well as the Sales Engineers who had first contact with our end users.
In fact, these were my primary audience; they were often literally on site with our customers while our end users engaged with the product, and that means my docs needed to minimize if not eliminate embarrassing frustrations.
It was not unusual for a support engineer to check in with me just before a release to ask if there were any surprises, or to make sure some aspect of the product was updated.

My docs were truly for such situations, if they were for anything at all.
When a product mentor from my own company was shoulder-to-shoulder with a user in a customer's IT department, both following along with my Reference Guide, I wanted them to find what they needed, where and when they needed it.
And of course I wanted them to find only accurate information, consistent wherever and however it was presented.

These frontline users were also often the first to discover bugs in my docs, which was of course invaluable for me.
The field teams needed a responsive system for submitting documentation bugs, and I needed them to feel empowered to contribute heavily and directly to resolving docs bugs.

--

That may sound like a lot of pressure and a lot of varying interests to satisfy, and I admit that's often how it felt.
Whenever this task seemed like exploring some uncharted territory of technical documentation, I just remembered I worked on a team that includes ReactJS coders, a machine-learning engineer, a whole bunch of Big Data platform engineers, and DevOps engineers (don't tell them I called them that -- it's complicated).

Note the consistency of these interests just among my collaborators.
_SOARCE_ truly covers the whole array.
If I maintain and facilitate good docs, everybody wins, even if almost nobody notices.

If, however, I fail to achieve those objectives, everybody notices.
So there's that.

=== Constituents' Single Source of Truth

There are two major motivations for single-sourcing our product documentation.
One is to enable us to express the same fact in multiple places without worrying about having to maintain that fact in more than one spot.
The other is to enable collaboration, with multiple collaborators able to edit the same source at the same time and reconcile any conflicts that ensue.

In later chapters, we will explore specific technical methods for single sourcing, but the most basic element is not a clever utility like Asciidoctor, Sphinx, or Jekyll.
The most basic element of collaborative DRY documentation development is Git itself.
Learning to work collaboratively on docs with other sophisticated technical professionals means learning to use Git.

== Git

// TODO section start

== Collaborating with Users

All of the above is not even to have mentioned the end users themselves, or with developers extending the product for their own end users.

Most open source projects and an increasing number of contributor-driven commercial outfits are encouraging users to contribute directly to docs.

=== The Old Ways

Wikis::
The most recent wave of collaborative documentation may just be the second wind of the last collaborative craze. It stems from very mixed, and probably mostly negative, experiences with opening wikis up to user contrubutions.

Discussion Boards::
Once upon a time (still more often than I can bear), bulletin boards and discussion forums have been used in the service of documentation.
Forums could be used to solicit participation and feedback which in turn informs and improves official documentation, such as managed knowledge bases, use cases, and tutorials.
But the technology must be applied with great care.
+
Sometimes, however -- and let's face it, drearier times -- discussion forums are used as the docs themselves.
Maybe a developer initiates threads in some of the channels, but each becomes a free-for-all of guesses and what-ifs, sometimes spiraling into flame wars.
These arrangements become never-pruned unofficial knowledge bases, mixing support requests with complaints and bad user advice with tardy official responses.
Better to leave these platforms to the likes of StackOverflow, keeping them off-site and third party.

IRC::
IRC channels are ephemeral, flowing, and conversational formats, where one might expect to find an edge-case request mentioned, but no one would think to consider a sacred source of truth, something more valuable can be built.
They are relatively anonymous, and somewhat hit or miss.
Nevertheless, they always seem to have an authentic feel.
A lot of times you get direct, realtime and symmetrical dialog with somene central to the project you need help on, right when you need that help.
There's something to be said for that.
+
The limitations of IRC are obvious.
With the more recent wave, given chat platforms like Gitter and Slack, product teams are interacting with extension developers and users in real time, with some sense of organization, flow, and a reliable archive.
It seems to me these contemporary tools haven't necessarily attracted the trolls or the Google-overloading wastelands that stale Discussion Board pages become.
+
But in the end, I'm not sure I would include this category as documentation.
Even if technical writers participate from time to time or derive content from such sources, I think its lack of permanence or adherence to SOARCE disqualifies it.

// TODO section-wrapup

=== Can User-Contributed Docs Be Done?

// TODO section-start
// Explore having users contribute to Git source through PR process
// Lots of examples between Docs Like Code and podcasts
