= Managing Complex Content

[abstract]
Technical content isn't only complicated from the macro perspective we took in the previous chapter.
Discrete content items can themselves be highly complex, like little clusters of data stored in a routine format, all of it yearning for expression in application code and user docs.
In this chapter we'll take a strategic look at handling complex content, including DRY single sourcing, validation, and collaborative workflow management.

== The Challenge

Handling what I call complex content objects (CCOs) is one of the biggest challenges faced by a team dealing with lots of distinct, structured content items.
I don't mean “chapters” or “topics”, as in the ways we modularize tech docs.
Instead, consider all the secondary and tertiary types of content you need to maintain and reuse to provide _references_ for users.

Think of reusable content items such as data your team is keeping in a spreadsheet right now -- the kind of content you wish you could port directly from engineers' internal documentation to your user-facing docs or UI, with just-in-time copy editing performed to boot.
If that engineers' reference spreadsheet has two or more _columns_, then each _row_ is a CCO.
Each such spreadsheet is a _collection_ of CCOs.

A glossary is a collection of CCOs, as is an API reference.

=== A Simple Example

CCOs are typically at least one step more complex than a parameter (a key-value pair).
But let's start with a relatively "simple" form of CCO that maybe wouldn't normally induce us to seek a radical new solution to managing this content.
For now, a simple parameter serves as a good warm-up example for exploring this topic.

.Example -- A parameter (in YAML)
[source,yaml]
----
my-key: some value for this key
----

Okay, we've got a key-value pair all right, but that's still pretty abstract.
How about a more useful example?

.Example -- A useful parameter
[source,yaml]
----
"glossary term": The definition for the glossary term
----

Now we're getting somewhere.
Let's try a real example by calling a snippet from one of the _Codewriting_ source files.

.Example -- Real data from data/glossary.yml
[source,yaml]
----
include::../_data/glossary.yml[tags=cco-example]
----

What are some real-world uses for this?

The most obvious one is to generate the glossary at the back of this book, which it does.

Of course, I could have just written the Glossary in AsciiDoc markup, which is pretty much equally elegant, maybe even a little nicer:

.Example -- The same glossary snippet sourced as AsciiDoc
[source,asciidoc]
----
complex content object::
  Abbreviated CCO, this is an item that may be more metadata than content, stored many to a file, as opposed to more typical text content units like chapters or topics, which may have some metadata but are mainly text and images.
  See <<complex-content-objects>>.

DITA::
  Acronym for _Darwin Information Typing System_.
  An XML standard designed for technical writing, introduced by IBM in 2005.
  In addition to a markup standard, DITA incorporates dynamic functionality and mature framework elements.
  link:https://en.wikipedia.org/wiki/Darwin_Information_Typing_Architecture[Wikipedia].

DRY::
  For "don't repeat yourself", referring to a single-sourcing approach to code or docs.
----

That markup is perfectly fine, and in fact it is the form the Glossary started in when I first began writing this book.
The only real problem with storing content/data in this format is it's not portable; only AsciiDoc tools can do anything with it out of the box, and there aren't many AsciiDoc tools that focus on manipulating complex content objects.

What if I wanted to be able to transform these glossary terms where they actually appear in the body of my book -- everywhere _except_ the glossary itself?
Perhaps in the HTML edition, I want to highlight the terms wherever they appear in the main text, so if users hover over or click on them, they'll see the definition in a tooltip above the word.

// TODO: add illustration

In order to do this, I need a convenient way to handle and reformat just the term I need.
AsciiDoc is not very helpful here, since it does not provide content to external tools as defined, semi-structured data like data-focused markup such as XML, JSON, and YAML.
Already, we've discovered a reason we should look at storing _all_ discrete, parameterized content as semi-structured or structured data.

=== Data Structure Terms

I'm going to use several descriptors for the format in which content can be stored “on the backend”.
That is, the form in which we hold our content so it can be best accessed in all the ways a product team might need it.
We handle each class of content differently, especially when the content is better described as data_ than as _text_.

unstructured text::
  This could be prose, or it could be gobbledigük.
  This could be a plain text file with words or data dumped in it, but I'll more likely refer to unstructured data in terms of open form textarea fields that may permit markup but do not enforce any structure.
+
[source,text]
.Unstructured Content Example
----
This is a box
  of unstructured content.

  You may have some expectation that this text
will be rendered in the shape it was
       entered.

Or
maybe not.
----
+
Just for the record, here is how that content looks after being processed by an AsciiDoc interpreter.
+
====
This is a box
  of unstructured content.

  You may have some expectation that this text
will be rendered in the shape it was
       entered.

Or
maybe not.
====

structured text::
  Text-heavy documents, whether or not governed by a schema, are considered structured content if they respect standardized formatting and an orderly, hierarchical document model.
  Depending on the application, users may treat such documents with strict regard to a document model or schema, or they may abuse intended strictures and conventions.
  In either case, we'll use _structured text_ to describe formats that adhere to some rhyme or reason.
+
[source,markdown]
.Structured Content Example
----
# Structured Content

In Markdown, the `#` symbol indicates the header level.
----

semi-structured data::
  This refers to content in recognized formats such as JSON, YAML, XML, CSV, at least some of which needs to be handled very much like data.
  These items tend to appear many to a page; they often convey looped content of interest more for reference than reading.
+
[source,json]
.Semi-structured Data Example (JSON)
----
{
  "key": "some_property-name",
  "property": "some.property-name",
  "section": "General",
  "description": "This is some text in `AsciiDoc`, with *bold*.\n",
  "default": 15,
  "hidden": false,
  "example": "some.property-name = 22",
  "openblock": ".Example Two\n----\nThis is some text that will convert to a code listing.\n----\n"
}
----
+
Imagine a collection of such property CCOs listed like a directory.

structured data::
  Schematified data, as in databases (including RDB and NoSQL) or XML with schema validation.
  This generally includes datasets that can be managed through queries.
+
[source,sql]
.Structured Data Example
----
CREATE TABLE IF NOT EXISTS data (
default INT,
description VARCHAR(46),
example VARCHAR(23),
hidden VARCHAR(),
key VARCHAR(18),
openblock VARCHAR(78),
property VARCHAR(18),
section VARCHAR(7)
);
INSERT INTO data VALUES
(15,'This is some text in `AsciiDoc`, with *bold*.
','some.property-name = 22',false,'some_property-name','.Example Two\\n----
This is some text that will convert to a code listing.\\n----\\n','some.property-name','General');
----

As you can deduct from the examples above, schemas can be advantageous.
For starters, they can define the data type and constrain each value.
With no such safeguards, semi-structured formats are open to invalid entries.

The disadvantage can also be seen: structured databases do not lend themselves well to representation as text/code, let alone to management in flat files.
We'll look at more of the reasons I think _semi-structured_ data is the technical communicator's Goldilocks data class.

=== Digging Deeper

We've seen how even simple key-value paired content can be output in unconventional ways, rather than always dumped as a list in whatever form it arrived.
Now let's take a deeper look at a kind of content that requires even more flexibility.

.Example -- A Complex Content Object or CCO (in YAML)
[source,yaml]
----
my-key:
  slug: mykey
  description: The key to your project.
  required: true
  type: string
  max-length: 20
----

The best example of a CCO type that I know of was my personal white whale: a means of cataloguing hundreds of configuration properties in a multi-component enterprise IT Ops product.
Our product was server software -- about a dozen distinct daemons that ran across scores of nodes at massive, multi-datacenter operations.
Our users could configure all of these services in myriad ways by setting key-value pairs through various configuration interfaces.

Let's get some more views of a configuration setting and all of its properties, so we can appreciate how flexible our source needs to be.

.Example -- Our product setting in the eyes of a user
====
[cols="1,3",frame=none,grid=none]
|===
s| My Key*:
|
2+| The key to your project.
|===
====

.Example -- And in the eyes of a front-end dev (1)
[source,json]
----
{
  "my-key": {
    "slug": "mykey",
    "description": "The key to your project.",
    "required": true,
    "type": "string",
    "max-length": 20
  }
}
----

JSON is the format in which JavaScript organizes data, and it's the most-common format for transmitting data to or from REST APIs.

.Example -- Again, our setting as also seen by a front-end dev (2)
[source,xml]
----
<input
  type="string"
  name="{{ slug }}"
  id="field-{{ slug }}-input"
  value="{{ value }}"
  data-validation="maxlen: {{ max-length }}" />{{ required }}
<span class="description" id="field-{{ slug }}-description">{{ description }}</span>
----

Notice that in this example the properties do not even appear in the same order; it's more than a matter of reskinning the same old data with different markup.

.Example -- And our product setting in the eyes of a back-end dev
[source,java]
----
public createKey(String type, String slug, String description, Boolean required) {
  this.type = type;
  this.slug = slug;
  this.description = desc;
  this.required = false;
}
----

As you can see, a simple product setting parameter can be useful in diverse settings:

. the documentation about that parameter
. in the interface where users can edit the property and appreciate an inline description
. in the back-end code that actually uses the setting to determine the product's functionality

Users need reliable access to accurate documentation of these settings, in the appropriate context of the component they're meant to configure.

Let's take a look at a the attributes of a more-complete configuration property as a YAML structure.
As you examine this figure, try to ignore the format and focus on the qualities of the content object.

.A complex content object (CCO) represented in YAML
[source,yaml ]
----
include::../includes/snippets/cco-property.yml[]
----

Even at a glance, you should be able to appreciate what makes this content “complex”.
As we see in the above snippet, a multi-version, multi-environment product could quickly require a relatively complex data structure to track how its configuration parameters relate to the product's various states and forms.

.Cloud Collaboration in Google Sheets
****
A lot of people hate Google Docs.
I am sympathetic, but I am not among them.
There have been countless frustrations with Google's authentication system and its quirky UI, but the truth is, I've made heavy use of each component in the Google Docs playground.
Each has its legitimate uses, even if all are overused.

Consider Google Sheets as a collaborative CSV-management system.
So long as you can export to the commonly-readable CSV format, you can port data managed by developers in Google sheets into just about any documentation output form imaginable.

For some content, this or some other live spreadsheet might be the shortest route to keeping fast-changing data as current as humanly possible.
This is doubly true when not all of your users are developers adept at working in flat files; most project managers and a huge range of SMEs will be comfortable with spreadsheets.

When content in a cloud-hosted spreadsheet changes, export the .CSV file into your source repo and use it to generate new output.
****

=== Considerations

The following factors must be taken into account when strategically addressing a CCO management problem.

authoring access::
Is this system going to be someone's sole domain, or is it a crowdsourced effort of two or more?

automation::
If your docs are integrated with a build system, it will have implications on your choice of toolchain for this functionality.

product versioning::
If by some stroke of genius or simplicity your product does not require release version control, you may be able to get away with a conventional CMS backed by a relational database (RDB).
The need to tie complex content with its corresponding product version argues for a flat-file approach, with settings kept in direct alignment with product code.

advanced data operations::
Will you need to *sort* CCOs by any of their parameter values?
How about *filtering* to output only certain instances of a CCO type in certain places?
Think once more in terms of that spreadsheet; sorting and filtering are key features.
Consider if you will ever need to re-sort your CCOs for publication (beyond just reformatting each CCO entry with a template).
+
Similarly, consider whether you'll need to combine data from different sets.
This is most conveniently done with SQL, which has a concept of _unions_ between data tables.

output formats::
What formats will your CCOs need to be output into?

* Markdown
* AsciiDoc
* reStructuredText
* XML
* HTML
* DITA
* Docbook
* LaTeX
* PDF
* Man
* JSON

Your solution will need to be mappable to all the required formats.
It will need to be exportable to something their tools can read, or external resources will need access to your CCO source directly and parse their needs from it.

output languages::
Internationalization support will either require another layer of development skill and effort or a budget for a CCMS with these capabilities built in (and of course suiting all your other CCO needs).

quantity of objects::
I don't know what the ceiling is, but there is certainly a limit to how many such objects can be sensibly managed in anything but an indexed database table.
A spreadsheet application is such a tool for small data like we're talking about.
It likely does not make sense to use flat files for datasources with several hundred or more entries.

relationality::
No matter how many records you're keeping track of, once they need to correlate to differently structured records, your options get pretty limited.
Flatter solutions work for records of self-contained data.

==== Data Dynamism

This is the inclusion of *variable data* and *tokenized data expression* inside a datasource, especially for cumulative inheritance of values set in a linear fashion.
Not the first or most-common consideration, data dynamism should be among your criteria.
Since this is a major shortcoming of the RDB model, it is a place where flat-file approaches might shine.
Give me a moment to explain:
In source code, parameters are often built cumulatively.
We are even able to do this in AsciiDoc.

.Example of cumulative parameter setting in AsciiDoc
[source,asciidoc]
----
:domain: codewriting.org
:domain_url: http://{domain}
:domain_url_ssl: https://{domain}
:blog_url: {domain_url_ssl}/blog
----

This way, we don't have to repeat `codewriting.org` in a bunch of places, risking that we might introduce a typo and making it harder to change when we get sued over trademark intrusion and forced to pick a new domain.

The problem, as noted earlier, is data defined in AsciiDoc is useless to other toolchains.
Besides this, we would much prefer to define variables with hierarchy and nesting.

If we want our product data to be available throughout our development environment, we're stuck with a semi-structured language like YAML.

.Example of static parameter setting in YAML
[source,ruby]
----
domain: codewriting.org
  url: http://codewriting.org
    ssl: https://codewriting.org
blog:
  url: https://codewriting.org/blog
----

This is useful, but even in such a small sample, the cause of my frustration is laid bare: the string `codewriting.org` is listed four times.

We can express a hierarchy and nesting, which is useful to most programming languages.
Unfortunately, it is not useful for AsciiDoc, which requires flat variables.

What if we could flatten our data structures and add variables based the key-value pairs we've already defined?

.Example of _cumulative_ parameter setting in YAML
[source,ruby]
----
domain: codewriting.org
  url: http://$domain
    ssl: https://$domain
blog:
  url: $domain_url_ssl/blog
----

Here our tokens are defined using the format `$some_key-1` (alphanumeric chars, underscores, or hyphens).
Flattened and parsed, this structure would read like so:

.Example of flattened and parsed parameters in YAML
[source,ruby]
----
domain: codewriting.org
domain_url: http://codewriting.org
domain_url_ssl: https://codewriting.org
blog_url: https://codewriting.org/blog
----

This elegant conversion can be ingested into Asciidoctor as variables.
In AsciiDoc, the expression `{blog_url}` would resolve to `https://codewriting.org/blog`.

== Solution Approaches

As a codewriter, I'm always leaning for the flat-file approach, but as you can see, it's not always going to make sense.
Before we settle on the flat file, let's seriously consider some other options.

=== Relational Databases

If your background is in website development or content management systems, the solution may seem obvious.
As recently as a couple years ago, I would have solved this with a relational database.
Structured Query Language is not just a way of inserting, updating, and retrieving data in a relational database;
it can also express the proper schema of a data object.
After all, a database table is basically a container for data objects, and the container is eminently configurable.

One major problem with the RDB solution is version control.
Source-control systems like Git don't work to track the innards of relational databases, which tend to use binary files.
Git has no insight into the structure of your conventional RDB file, so it cannot track changes made to the data.
Therefore, an RDB will also require specific version tagging of any version-sensitive data, a layer of manual complexity that is fairly prohibitive.
One of the reasons we're doing docs-as-code in the first place is so that we can associate our single-sourced product info with the version of the product to which it applies

The other major limitation of using RDBs for a constantly changing array of datasets is the interface.
RDBs require query transactions to access data, including for reading and writing.
This can be abstracted into form interfaces, as with a traditional CMS, but then that CMS has to be administered and maintained.

A good, open CMS platform such as Drupal provides your product build system with REST API access to your human-maintained data.
So if you are willing and able to maintain such system, an external CMS can work with a docs-as-code solution.
If the demands of your product will be relatively static -- meaning, no new forms of complex data popping up all the time, maybe an RDB plus a web-based interface and straight JDBC/SQL on the back end can solve your needs.
As an old hand with Drupal and WordPress, I always consider a dynamic, server-side solution when I encounter a new challenge.

However, the factors mitigating the RDB-backend and web-UI solution are very strong compared to the relative freedom and ease of a flat file.
Sure, you'd never open a flat-file datasource to just any user, but in a professional environment with a proper workflow in place for vetting new content, flat files are superior low-volume datasources.

=== DITA CCMS

The DITA system's *specialization* feature can be used to define and maintain CCOs.
So DITA platforms naturally come ready to handle this issue using an elegant interface with XML “under the hood”.
I'd call that a pretty significant advantage.

One limitation of these systems is they require special tools: editors that manage content.

Most DITA CCMSes seem to use relational database back ends, though some now handle flat-file storage and integrate nicely with Git.

Whether content is stored in an RDB or in flat files, the platform is enhanced by a database-backed content-management interface.
The advantages of this are significant, including powers for reorganizing content that are tedious and clumsy to do with conventional file-management tools.

Unfortunately, those special tools really do add expense and weight.
License fees range from $50 to hundreds of dollars a month _per seat_, making it prohibitive to involve all SMEs as docs contributors.
Despite my idealistic description above, these tools also tend to be somewhat clunky, and they are very much Windows-oriented.
Engineers tend to dislike clunkiness and Windows, not coincidentally.

// TODO section-research
// Investigate if DITA CCMSes integrate with build systems.

Localization and translation management are another major advantage of DITA-based systems.
If you need to generate documentation in multiple languages and do not wish to reinvent this (very complicated) wheel, proprietary CCMSes or major open source CMSes are probably your best options.

=== Flat Files

At Rocana, we strongly desired to keep our complex content in flat files.
AsciiDoc has not proved suitable for this situation.
It falls down in several places.
Complex content written in AsciiDoc is not even proper data; there is really no way to interact with discrete items outside AsciiDoc tooling.

We also needed to be able to output complex content in several distinct formats, including:

. sample configuration files in what's called “INI format”, a dreadfully plain blob conventional to Java platforms;

. Reference Guide sections in the chapter “Configuring Rocana Ops”, which is sourced in AsciiDoc and published as both HTML and PDF;

. GUI forms for central configuration of remote components via our web application;

. an internal Knowledge Base where hidden configuration settings and troubleshooting advice can be accessed by engineers and support agents, but not necessarily all end users;

. similarly to the Glossary example, our online Reference Guide and other materials could generate a tooltip for whenever text is hovered, exposing more information about specific settings wherever those settings are referenced in the text.

As you can see, I had big plans and high hopes for all that complex content.

The challenge was to

. allow engineers to maintain YAML files as they manage the rest of their code

. without sacrificing any of the ways this material was already being delivered (AsciiDoc and INI files), and meanwhile

. add the ability to integrate data directly into the application

. from a single source, possibly external to both docs and product code.

After months of hemming and hawing over the best way, which included talking with consultants about how to handle the matter, I finally sat down and took a shot at coding a solution.

== Introducing “LiquiDoc”

My system is simple.
It's a little command-line tool that ingests data, passes that data to templates for variable substitution, and then saves copies of the populated templates as new files in the appropriate format.
A simple configuration system lets me coordinate source files (YAML) with templates (Liquid) to save the results as.

.Example -- LiquiDoc Coordination File
[source,yaml]
----
- action: parse
  data: data/data-sample.yml
  builds:
  - template: templates/tpl-sample.asciidoc
    output: output/sample-consumer.adoc
  - template: templates/tpl-sample.ini
    output: output/sample-consumer.properties
----

What follows is an example data source file.
It contains metadata about the topic (this collection of settings) as well as a couple of dummy settings.

[[liquidoc-source]]
.Example -- LiquiDoc Source Data File
[source,yaml]
----
meta:
  title: Platform # Template will append "Settings"
  description: |
    This is some awesome text that describes the platform settings displayed on this page and anything particularly special about it. Feel free to use AsciiDoc formatting here, as it will be parsed.
  sections: # List all of the categories of properties in this file
    - name: Basic
    - name: Security
      instructions: Be careful with these!

settings:
  - key: some_setting-name
    setting: some.setting-name
    section: General
    description: This is some text in `AsciiDoc`, with *bold*.
    default: 15
    required: true
    example: some.setting-name = 22

  - key: another_setting-name
    setting: another.setting-name
    section: Security
    description: A different description for this _resource_.
    default: true
    required: false
    example: |
      # This should appear as a literal.
      another.setting-name = whatever
----

// TODO Add genericized example files from LiquiDoc boilerplate

=== Flat-file shortcomings

Remember that concept of _relationality_ in small data that I brought up earlier?
Where
There are ways to sensibly “join” two semi-structured data files the way an RDB joins tables, but it's clunkier than a system with a true database backing it.
If you have files named `people.yaml` and `jobs.yaml`, you're going to have an uphill battle keeping people associated with their jobs, and jobs associated with the people performing them.
It's not an impossible problem to address down to this layer of complexity, but only a real product-development process will nail the architecture, interface, and query language for handling such relationships for highly complex small data in flat files.

=== Where This is Going

Imagine the value of having canonical product data in semi-structured format, sitting side-by-side with product source code.
This solution allows version control to keep information _about_ the code up to date with the code itself.

Hardcore engineers will balk at the idea of storing generated source alongside its own source.
Since everything has a source, radical programming requires stripping everything to its roots.
Ideally, nobody should be able to mistake generated source for the code it was drawn from.

This would be the case were you to store data in a format such as YAML, then generate Markdown or AsciiDoc files from that code and commit them to the same repo as the YAML source.
Now you have the same content committed to the same repo in two different places, one of which is entirely depending on its actual source.
The source-control purists are actually right: this is poor form and an accident waiting to happen.
It may also be the best option for keeping your docs in great shape, so argue for it if you need to.

The better argument, however, would be for continuous integration.
With CI, the product build will just call a script, and the AsciiDoc/Markdown source files will be generated during the build, then rendered along with the rest of the docs as if they'd been sitting there all along.
If you are not authorized or skilled enough to hack the build, maybe you can recruit a DevOps/automation engineer to champion this level of real-time integration.

Finally, the real coup is when engineers start using your semi-structured data files as source libraries for their product code.
If an engineer is hacking your YAML file to document a configuration property, including its metadata (data type, constraints, required status, etc), why wouldn't that engineer just use your YAML file as the _source_ of that metadata to help define their code?
Any YAML file can be a library or data source for other aspects of the product.
This is how we establish canonical data in DRY, single-sourced complex content systems.

// TODO more on LiquiDoc, including examples
