= Managing Complex Content

[abstract]
Technical content isn't only complicated from the macro perspective we took in the previous chapter.
Discrete content items can themselves be highly complex, especially when those content items need to be delivered in various ways.
In this chapter we'll take a strategic look at handling complex content.

Handling what I call complex content objects (CCOs) is one of the biggest challenges faced by a team dealing with lots of distinct, structured content items.
A content object is semi-structured data you deal with in every page, article, or topic of content you write in any markup language.
The markup is structuring a complex content object, even adding metadata of at least some kind (minimally dates such as when created and modified).

== The Challenge

What I mean by CCOs are all the secondary and tertiary types of content you need to maintain and reuse.
Besides pages and their subordinate content objects (such as blocks, links, and so forth), you probably need your documentation solution to handle an array of less-standard items or collections of items, including product metadata and settings.
Think of reusable content items such as data you're keeping in a spreadsheet right now.
If it has two or more columns, each row is a CCO, and each spreadsheet is a CCO collection.

=== A Simple Example

CCOs are typically at least one step more complex than a parameter (a key-value pair).
But let's start with a relatively "simple" form of CCO that maybe wouldn't normally induce us to seek a radical new solution to managing this content.
For now, a simple parameter serves as a good warm-up example for exploring this topic.

.Example -- A parameter (in YAML)
[source,yaml]
----
my-key: some value for this key
----

Okay, we've got a key-value pair all right, but that's still pretty abstract.
How about a more useful example?

.Example -- A useful parameter
[source,yaml]
----
"glossary term": The definition for the glossary term
----

Now we're getting somewhere.
Let's try a real example by calling a snippet from one of the _Codewriting_ source files.

.Example -- Real data from _data/glossary.yml
[source,yaml]
----
include::../_data/glossary.yml[tags=cco-example]
----

What are some real-world uses for this?

The most obvious one is to generate the glossary at the back of this book, which it does.

Of course, I could have just written the Glossary in AsciiDoc markup, which is pretty much equally elegant:

.Example -- The same glossary snippet sourced as AsciiDoc
[source,asciidoc]
----
complex content object::
  Abbreviated CCO, this is an item that may be more metadata than content, stored many to a file, as opposed to more typical text content units like chapters or topics, which may have some metadata but are mainly text and images.
  See <<complex-content-objects>>.

DITA::
  Acronym for _Darwin Information Typing System_.
  An technical writing-oriented XML standard introduced by IBM in 2005.
  Pronounced _DII-tuh_, not _DEE-tuh_ or _DIE-tuh_.
  https://en.wikipedia.org/wiki/Darwin_Information_Typing_Architecture[Wikipedia].

DRY::
  For "don't repeat yourself", referring to a single-sourcing approach to code or docs.
----

That markup is perfectly fine, and in fact it is the form the Glossary started in when I first began writing this book.
The only real problem with storing content/data in this format is it's not portable; only AsciiDoc tools can do anything with it out of the box, and there aren't many AsciiDoc tools that focus on manipulating complex content objects.

What if I wanted to be able to transform these glossary terms where they actually appear in the body of my book -- everywhere _except_ the glossary itself?
Perhaps I want to highlight the terms where they appear, so if users hover over or click on them, they'll see the definition in a tooltip above the word.

// TODO: add illustration

In order to do this, I need a convenient way to handle and reformat just the term I need.
Already, we've discovered a reason we should look at storing _all_ discrete, parameterized content as semi-structured or structured data.

.Data Structure Terms
****
I use terms for data structure types that most computer scientists would probably disagree with.
The primacy of the specific problems faced by content managers renders additional distinction.

unstructured content::
  This could be prose, or it could be gobblediguk.
  This could be a plain text file with words or data dumped in it, but I'll more likely refer to unstructured data terms of open form textarea fields that may permit markup but do not enforce any structure.

structured content::
  Text-heavy documents, whether or not governed by a schema, are considered structured content if they respect standardized formatting and an orderly hierarchical document model.
  Depending on the application, users may treat such documents with strict regard to a document model or schema, or they may abuse intended strictures and conventions.

semi-structured data::
  This refers to content in what are JSON, YAML, XML, CSV, and other forms of content, at least some of which needs to be handled very much like data.
  These items tend to appear many to a page, as they convey looped content of interest more for reference than reading.

structured data::
  Schematified data, as in databases (including RDB and NoSQL) or XML with schema validation.
  This generally includes datasets that can be managed through queries.
****

=== Digging Deeper

Now that we've seen how even simple key-value paired content can be output in unconventional ways, rather than always dumped as a list in whatever form it arrived, let's take a deeper look at a kind of content that requires even more flexibility.

.Example -- A Complex Content Object or CCO (in YAML)
[source,yaml]
----
my-key:
  slug: mykey
  description: The key to your project.
  required: true
  type: string
  max-length: 20
----

The best example of a CCO type that I know of is my personal Moby Dick: a means of cataloguing hundreds of configuration properties in a multi-component enterprise IT Ops product.
Our product is server software -- about a dozen distinct daemons that may run across scores of nodes at a massive, multi-datacenter operation.
Our users can configure all of these services in myriad ways by setting key-value pairs through various configuration interfaces.

Let's get some more views of a configuration setting and all of its properties, so we can appreciate how flexible our source needs to be.

.Example -- Our product setting in the eyes of a user
====
[cols="1,3",frame=none,grid=none]
|===
s| My Key*:
|
2+| The key to your project.
|===
====

.Example -- And in the eyes of a front-end dev (1)
[source,json]
----
{
  "my-key": {
    "slug": "mykey",
    "description": "The key to your project.",
    "required": true,
    "type": "string",
    "max-length": 20
  }
}
----

.Example -- Again, our setting as also seen by a front-end dev (2)
[source,xml]
----
<input
  type="string"
  name="{{ slug }}"
  id="field-{{ slug }}-input"
  value="{{ value }}"
  data-validation="maxlen: {{ max-length }}" />{{ required }}
<span class="description" id="field-{{ slug }}-description">{{ description }}</span>
----

Notice that in this example the properties do not even appear in the same order; it's more than a matter of reskinning the same old data with different markus.

.Example -- And our product setting in the eyes of a back-end dev
----
TODO not sure which view to display here. Help wanted.
----

As you can see, a simple product setting parameter can live in diverse settings.
Wrangling these things in all their various incarnations can be a real pain.

Rocana's users need reliable access to accurate documentation of these settings, in the appropriate context of the component they're meant to configure, so they can deploy and fine tune our software.

Let's take a look at a more complete configuration setting's properties as a YAML structure.
As you examine this figure, try to ignore the format and focus on the qualities of the content object.

.A complex content object (CCO) represented in YAML
[source,yaml ]
----
include::../includes/snippets/cco-property.yml[]
----

Even at a glance, you should be able to appreciate what makes this content “complex”.
As we see in the above snippet, a multi-version, multi-environment product could quickly require a relatively complex data structure to track how its configuration parameters relate to the product's various states and forms.

=== Considerations

The following factors must be taken into account when strategically addressing a CCO management.

authoring access::
Is this system going to be someone's sole domain, or is it a crowdsourced effort?

automation::
If your docs are integrated with a build system, it will have implications on your choice of toolchain for this functionality.

product versioning::
If by some stroke of genius or simplicity your product does not require release version control, you may be able to get away with a conventional CMS backed by a relational database (RDB).
The need to tie complex content with product version argues for a flat-file approach, with settings kept in direct alignment with product code.

advanced data operations::
Will you need to *sort* CCOs by any of their parameter values?
How about *filtering* to output only certain instances of a CCO type in certain places?
Think once more in terms of that spreadsheet; sorting and filtering are key features.
Consider if you will ever need to re-sort your CCOs for publication (beyond just reformatting each CCO with a template).
+
Similarly, if you'll need to combine data from different sets, this is most conveniently done with SQL.
Heavy manipulation of semi-structured data is more difficult to program after the data has been ingested into your aps.

output formats::
What formats will your CCOs need to get output into?

* HTML
* Markdown
* AsciiDoc
* DITA
* Docbook
* LaTeX
* PDF
* Man
* JSON

Your solution will need to be mappable to all the required formats.
It will need to be able to export to something they can read, or external resources will need access to your CCO solution.

output languages::
Internationalization support will either require another layer of development skill and effort or a budget for localization CCMS capabilities.

quantity of objects::
I don't know what the ceiling is, but there is certainly a limit to how many such object can be sensibly managed in anything but a relational database.
Juggling lots of long text files is unweidly.

== Solution Approaches

As a codewriter, I'm always leaning for the flat-file approach, but as you can see, it's not always going to make sense.
Before we settle on the flat file, let's seriously consider some other options.

=== Relational Databases

If your background is in website development or content management systems, the solution may seem obvious.
As recently as a couple years ago, I would have solved this with a relational database.
Structured Query Language is not just a way of inserting, updating, and retrieving data in a relational database;
it can also express the proper schema of a data object.
After all, a database table is basically a container for data objects.

One major problem is version control.
Source-control systems like Git don't work to track the innards of relational databases, which tend to use binary files.
Git has no insight into the structure of your conventional RDB file, so it cannot track changes made to the data.
Therefore, an RDB will also require specific version tagging of version-specific data, a layer of manual complexity that is fairly prohibitive.

The other major limitation of using RDBs for a constantly changing array of datasets is the interface.
RDBs require query transactions to access data.
This can be abstracted into forms, as with a traditional CMS, but then that CMS has to be administered and maintained.
A good, open CMS platform such as Drupal provides your product build system with REST API access to your human-maintained data.

If the demands of your product will be relatively static -- meaning, no new forms of complex data popping up all the time, maybe an RDB plus a web-based interface and straight JDBC/SQL on the back end can solve your needs, go for it.
As an old hand with Drupal and WordPress, I always consider a dynamic, server-side solution when I encounter a new challenge.

=== DITA CCMS

The DITA system's *specialization* feature can be used to define and maintain CCOs.
So DITA platforms naturally come ready to handle this issue using an elegant interface with XML “under the hood”.
I'd call that a pretty significant advantage.

One limitation of these systems is they require special tools: editors that manage content.

Most DITA CCMSes seem to use relational database back ends, though some now handle flat-file storage and integrate nicely with Git.

Whether content is stored in an RDB or in flat files, the platform is enhanced by a database-backed content-management interface.
The advantages of this are significant, including powers for reorganizing content that are tedious and clumsy to do with conventional file-management tools.

Unfortunately, those special tools really do add expense and weight.
License fees range from $50 to over a hundred dollars a month _per seat_, making it prohibitive to involve all SMEs as docs contributors.
Despite my idealistic description above, these tools also tend to be somewhat clunky, and they are very much Windows-oriented.
Engineers tend to dislike clunkiness and Windows, not coincidentally.

// TODO Investigate if DITA CCMSes integrate with build systems.

Localization and translation management are another major advantage of DITA-based systems.
Thanksfully, this is not a requirement for my current product docs.

=== Flat Files

At Rocana, we strongly desire to keep our complex content in flat files.
AsciiDoc has proved fairly robust for this situation, but it falls down in a couple of places, namely the ability to rearrange complex content elements, as illustrated in the earlier Glossary example.

We also need to be able to output complex content in several distinct formats, including:

. sample configuration files in what's called “INI format”, a dreadfully plain blob conventional to Java platforms;

. Reference Guide sections in the chapter “Configuring Rocana Ops”, which is sourced in AsciiDoc and published as both HTML and PDF;

. GUI forms for central configuration of remote components via our web application;

. an internal Knowledge Base where hidden configuration settings and troubleshooting advice can be accessed by engineers and support agents, but not necessarily all end users;

. similarly to the Glossary example, our online Reference Guide and other materials could generate a tooltip for whenever text is hovered, exposing more information about specific settings wherever those settings are referenced in the text.

As you can see, I have big plans and high hopes for all that complex content.

The challenge is to:

. allow engineers to maintain YAML files as they manage the rest of their code

. without sacrificing any of the ways this material is already delivered (AsciiDoc and INI files), and meanwhile

. add the ability to integrate data directly into the application and docs.

After months of hemming and hawing over the best way, which included talking with consultants about how to handle the matter, I finally sat down and took a shot at coding a solution.

My system is simple. It's a script that can ingest data, pass that data to templates for substitution, and then saves the populated templates as new files in the appropriate format.
A simple configuration system lets me coordinate source files (YAML) with templates (Liquid) to save the results as.

.Example -- LiquiDoc Coordination File
[source,yaml]
----
- source:
  data: data/data-sample.yml
  builds:
  - template: templates/tpl-sample.asciidoc
    output: output/sample-consumer.adoc
  - template: templates/tpl-sample.ini
    output: output/sample-consumer.properties
----

What follows is an example data source file.
It contains metadata about the topic (this collection of settings) as well as a couple of dummy settings.

.Example -- LiquiDoc Source Data File
[source,yaml]
----
  meta:
    title: Platform # Template will append "Settings"
    description: |
      This is some awesome text that describes the platform settings displayed on this page and anything particularly special about it. Feel free to use AsciiDoc formatting here, as it will be parsed.
    sections: # List all of the categories of properties in this file
      - name: Basic
      - name: Security
        instructions: Be careful with these!

settings:
  - key: some_setting-name
    setting: some.setting-name
    section: General
    description: This is some text in `AsciiDoc`, with *bold*.
    default: 15
    required: true
    example: some.setting-name = 22

  - key: another_setting-name
    setting: another.setting-name
    section: Security
    description: A different description for this _resource_.
    default: true
    required: false
    example: |
      # This should appear as a literal.
      another.setting-name = whatever
----

// @TODO Add genericized example files from LiquiDoc

For now, I run this system manually whenever an engineer makes changes to a setting's definition, and that output gets added to the trunk along with the edits to the YAML source file, typically in the same merge request.
Eventually, continuous integration will remove this additional step, and our configuration properties will not exist as AsciiDoc files in the source codebase at all.
The build will just call my script, and those files will be generated during the build, then compiled along with the rest of the docs as if they'd been sitting there all along.
