= Asciidoctor, Jekyll, and Hyde for Elegant Docs out of the Box
:page-layout: post
:page-permalink: blog-asciidoctor-jekyll-hyde-docs-out-of-the-box
:page-date: 2017-11-06 13:27
:page-comments: true
:page-external-url:
:page-categories: [tooling]
:page-author: Brian Dominick
---

I swear I don't just love this stack because of the title it gives me.
I do admit “Hyde” wouldn't have made it into the title if it didn't just sound so good, but it's also a nice theme, as you can see.

In any case, that's what's under the hood of this site.
All pages and posts are written in link:http://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc] dynamic markup, converted to HTML by the link:http://asciidoctor.org/docs/what-is-asciidoctor/[Asciidoctor] rendering engine, built into a proper site by link:https://jekyllrb.com/[Jekyll] static generator with a lightweight theme called link:http://hyde.getpoole.com/[Hyde] giving the pages structure and style.
Then served on link:https://pages.github.com/[GitHub Pages].

[IMPORTANT]
.Update!
Now hosted on the fantastic link:https://www.netlify.com/[Netlify] continuous docs deployment platform!

I've been working with Jekyll and Asciidoctor for well over a year now, and I am confident that they are robust, pliable utilities that can solve a very wide range of technical documentation problems.
This is especially true when you consider the broad range of Asciidoctor output.

In this blog, I will journal some of my technical experiments in documentation tooling, much of it around Asciidoctor and my own free and open source tool, link:https://www.ajyl.org/liquidoc[LiquiDoc].
All of this tooling is FOSS, and it's all written in Ruby, which I started learning some months back in order to hack a complex docs build toolchains.
Now I'm looking for new projects and challenges, which i hope to trace here.

Not that I'm hacking or extending it, the other major tool all of this depends on is Git.

If you're a technical documentarian of any kind, consider checking out my book _Codewriting_.
I've set up an link:/blog-feed.xml[RSS feed], and I'll be posting links on my nascent Twitter account (link:https://twitter.com/_codewriter[@_codewriter]) as soon as I get my shit together.
