= A Note to Readers & Contributors

There is no sense in postponing my confession: I have written a user manual for the role of technical writer.
The first draft of that sentence contained a reference to _irony_, but in truth it is not at all ironic that technical writers ourselves require instruction.
I’ve strung together a lot of prose in my lifetime, but I’m casting this book project in a format I hope technical writers and software developers will appreciate:
lots of section headings, bulleted lists, sidebars, examples, code listings, and summaries.

But I'm also instilling this book with some rants, because I have things to express.
You are welcome to roll your eyes right past any objectionable passages.

[[tech-writer-journalist]]
[TIP]
.A tech writer is not a tech journalist
*Tech writers* _document and instruct_ a product on behalf of its _makers_ (usually _as one of its makers_).
By contrast, *tech journalists* _promote and praise_ products on behalf of the journalists’ _sponsors_, which are often those same products.

== Collaborative Authoring

I don’t want you to just read this book; _I want you to contribute to it_.

_Codewriting_ is a living document being written on a public GitHub repository.
You are welcome and encouraged to contribute by forking the repo, contributing edits, and issuing a pull request (PR).
For detailed instructions, see <<contributing>>.

Be sure to add your name to the contributors list with your PR!

== Writing to Learn

I have never gained proficiency at anything without writing about it in the process, even for an audience of one person I suspected was not even reading.
But I do not write as an expert, conveying my accumulated wisdom;
former journalist that I am, I write to motivate and structure research efforts during the intermediate part of a learning project.
I’m hoping you’ll at least follow along, if not chip in to teach me a thing or two.

[WARNING]
“Intermediate” may best describe my proficiency at technical writing, and then only because I join the field with nearly 20 years in software development and even longer writing professionally.
I won’t release editions of this book that contain known falsehoods, but it may always contain a significant amount of idiosyncrasies and shortfalls.
The field of technical writing is the only subject I handle that's more complicated, uncharted territory than the multi-component enterprise platform technology I document by day.

== Engaged Learning

As a technical writer, I like to use examples.
I also happen to learn best from examples.
Most importantly, I learn best by following along.

For these reasons, a narrative structure will be threaded throughout the book, and you are encouraged to play along.
All the tools you will need are introduced as they are called for.
Every tool used in these instructions will be free and open source software.
Examples in this book heavily favor AsciiDoc markup language, though daring participants are welcome to follow along in a markup language of their choosing.
The particular language should not matter for most examples.

If you succeed with parallel examples, please consider contributing them.

== Tech Writing Can Be Fun & Funny

I am enjoying writing this book, but I have to admit, not all technical writing is pleasureful.
For instance, the Reference Guide I maintained as the primary responsibility of my day job while I wrote most of this at night and on weekends was not always a page turner -- for reading or writing.
I got enjoyment out of many of the non-writing parts of that job, including working with great engineers and getting my hands dirty with their bleeding-edge software.
Still, we all know tech writing can be the opposite of pleasure writing.
Fussing over every word in an instruction step, trying to shorten code listing line lengths to fit the page, or just re-conveying the same banal concepts over and over; tech writing has its downsides.

It has been conveyed to me by people of good repute that joking and cursing in technical documentation for a “serious” enterprise product is a bad move.
I think that's bullshit, but I propose a compromise.
I will bite my tongue on the expletives, but let’s try to inject humor into this most dry of _crafts_.
It may never rise to the level of an _art form_, but I’ll take _craftsperson_ over _clerk_ as a job genus any day.

== Creative Commons License

I’m not trying to get rich or famous off this book (if that was not already obvious, you might be in the wrong place; _try <<tech-writer-journalist,tech journalism>>_).
You can take this text and do what you want with it, so long as you leave a crumb trail of credit as described in the <<creative-commons,copyright and licensing notice>>.

I would be honored if a free-thinking colleague ever decided to fork this, whether to contribute substantively and propose a re-merge, or to take this idea in another direction, even in their own voice -- _so long as you freely share anything you share at all_.

See the ground rules in the link:{github-repo-uri}/blob/prime/LICENSE.md[`LICENSE.md`] file.
