= LiquiDoc

== Anything in, anything out: for handling docs like code

=== What if you could take this:

[source,yaml]
----
# YAML
----

=== ...and from it generate documentation:

====
// add Asciidoc output
====

=== ...as well as UI definition

[source,html]
----
<!-- add html source -->
----

=== ...and even validation code

[source,json]
.JSON validation code for tests and formfield validation
----

----

== LiquiDoc is a framework and utility for true single-sourced engineering

From source to interface to docs, your product and what you say about it can finally be consistent.

=== LiquiDoc is free and open source software

To do our work right, technical documentarians need tools that integrate their workflow with that of product developing.
Whether you're a tech writer on a big team or a self-documenting lone-wolf programmer, you appreciate how difficult it is to keep a product's front and back ends consistent -- let alone keeping the docs up to date.

The key to consistency is maintaining a single source of truth.
Complex product data and content is unsafe outside the code repository.
It's bad enough that coders reference disconnected specification sources while working on API endpoints, configuration settings, primary interface elements, and discrete features.
Unit tests need to be written or updated.
The UI needs to be updated.
Once all that code is complete, that coder or someone altogether different has to write it all up as “the docs” in still another format.

_*Enough of this insanity!*_

=== The End of Divergence!

It's time to keep all your crucial product info as semi-structured data, right alongside your product code _and_ the rest of your docs.
LiquiDoc enables truly *treating documentation like source code*: write in dynamic lightweight markup langauges such as AsciiDoc and YAML, then generating content where and when it is needed, as well as directly informing the product.
At long last, canonical product source where it belongs -- _in the docs directory_ -- and always up to date.

=== Getting started with LiquiDoc

LiquDoc is a Ruby gem.
The fastest way to get up to speed is with codewriting.org's LiquiDoc Boilerplate project.
On Mac or Linux, you should be good to go.
If you're using Windows and lack Ruby, get it here.

. Clone or download and unzip the link:https://github.com/briandominick/github-boilerplate[Boilerplate repo].

. Open a terminal to the project directory and run:
+
----
bundle install
----
+
If it turns out you don't have Bundler, run `gem install bundler`

. You should be ready for your first LiquiDoc build.
+
----
bundle exec liquidoc -c _data/sample.yml` --verbose
----
+
This procedure draws data from files in various semi-structured data formats (YAML, JSON, XML, CSV) and builds multiple documents in different output formats.
Examine `_data/sample.yml` to see all the source, template, and output configurations.
